# Generated by Django 5.1.2 on 2024-10-26 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.URLField()),
                ('subjudul', models.CharField(max_length=500)),
                ('konten', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
