# Generated by Django 5.1.2 on 2024-11-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editProfile', '0001_initial'),
        ('search', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tried_foods',
            field=models.ManyToManyField(blank=True, to='search.food'),
        ),
    ]
