# Generated by Django 5.1.2 on 2024-10-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_foodentry_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodEntry',
        ),
    ]
