# Generated by Django 5.1.2 on 2024-10-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodentry_description_foodentry_food_foodentry_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='food',
            new_name='name',
        ),
    ]
