# Generated by Django 5.1.2 on 2024-10-21 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_food_foodentry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
