# Generated by Django 5.1.2 on 2024-10-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_foodentry'),
        ('main', '0005_alter_foodentry_description_alter_foodentry_name_and_more'),
    ]

    operations = [
    ]
