# Generated by Django 5.1.2 on 2024-10-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodreview',
            old_name='review_content',
            new_name='review_message',
        ),
    ]
