# Generated by Django 5.1.3 on 2024-11-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_foodreview_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodreview',
            unique_together=set(),
        ),
    ]
