<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-26 17:16
=======
# Generated by Django 5.1.2 on 2024-10-23 11:05
>>>>>>> 4cde0acca1382f7d89aa46bcd2db4087c57ed83e

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('search', '0005_delete_customuser'),
=======
>>>>>>> 4cde0acca1382f7d89aa46bcd2db4087c57ed83e
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.food')),
=======
            name='FavoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
>>>>>>> 4cde0acca1382f7d89aa46bcd2db4087c57ed83e
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
