# Generated by Django 5.1.2 on 2024-10-26 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_favoritefood'),
        ('search', '0005_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'food')},
        ),
        migrations.DeleteModel(
            name='FavoriteFood',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
