# Generated by Django 5.1.2 on 2024-10-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_customuser_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
