# Generated by Django 5.1.2 on 2024-12-20 16:47

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "foods")


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_delete_customuser'),
    ]

    operations = [
    migrations.RunPython(load_my_initial_data),
]
