# Generated by Django 5.1.4 on 2024-12-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_food_deskripsi_alter_food_gambar_and_more'),
        ('search', '0006_auto_20241220_2347'),
    ]

    operations = [
    ]
